// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*

version = "2025.07"

project {

    buildType(DebugBuild)
    buildType(ReleaseBuild)
    buildType(PublicBuild)
    buildType(PublicDeployment)
    buildType(UpstreamMerge)
    buildType(Bump)
    buildType(PrePublish)
    buildType(PostPublish)

    buildTypesOrder = arrayListOf(DebugBuild,ReleaseBuild,PublicBuild,PublicDeployment,UpstreamMerge,Bump,PrePublish,PostPublish)

}

object DebugBuild : BuildType({

    name = "Build [Debug]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_MetalamaConsolidated"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalamaconsolidated-2026.1"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalamaconsolidated-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalamaconsolidated-2026.1 -NoBuildImage test --configuration Debug --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Metalama_Metalama20261_MetalamaConsolidated"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Metalama_Metalama20261_MetalamaConsolidated"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2026.1"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

    dependencies {
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Community"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Documentation"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Premium"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Samples"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaTests_MetalamaTestsNopCommerce_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
     }

})

object ReleaseBuild : BuildType({

    name = "Build [Release]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_MetalamaConsolidated"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalamaconsolidated-2026.1"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalamaconsolidated-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalamaconsolidated-2026.1 -NoBuildImage test --configuration Release --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Metalama_Metalama20261_MetalamaConsolidated"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Metalama_Metalama20261_MetalamaConsolidated"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2026.1"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

    dependencies {
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Community"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Documentation"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Premium"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Samples"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaTests_MetalamaTestsNopCommerce_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
     }

})

object PublicBuild : BuildType({

    name = "Build [Public]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_MetalamaConsolidated"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalamaconsolidated-2026.1"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalamaconsolidated-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalamaconsolidated-2026.1 -NoBuildImage test --configuration Public --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Metalama_Metalama20261_MetalamaConsolidated"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Metalama_Metalama20261_MetalamaConsolidated"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2026.1"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

    dependencies {
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Community"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Documentation"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Premium"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Samples"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaTests_MetalamaTestsNopCommerce_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
     }

})

object PublicDeployment : BuildType({

    name = "Deploy [Public]"

    type = Type.DEPLOYMENT

    params {
        text(
            "Publish.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Publish' build step.", allowEmpty = true)
        param("Publish.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_MetalamaConsolidated"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalamaconsolidated-2026.1"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalamaconsolidated-2026.1 "
        }
        powerShell {
            name = "Publish"
            id = "Publish"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalamaconsolidated-2026.1 -NoBuildImage publish --configuration Public --timeout %Publish.Timeout% %Publish.Arguments%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

    dependencies {
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_PublicDeployment")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Community"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_PublicDeployment")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicDeployment")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Documentation"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_PublicDeployment")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Premium"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_PublicDeployment")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_PublicBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Samples"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_PublicDeployment")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaTests_MetalamaTestsNopCommerce_PublicDeployment")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(PublicBuild) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/public/**/*=>artifacts/publish/public\n+:artifacts/publish/private/**/*=>artifacts/publish/private"
            }
        }
     }

})

object UpstreamMerge : BuildType({

    name = "Upstream Merge"

    params {
        text(
            "UpstreamMerge.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Merge upstream' build step.", allowEmpty = true)
        param("UpstreamMerge.Timeout", "15")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_MetalamaConsolidated"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalamaconsolidated-2026.1"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalamaconsolidated-2026.1 -Dockerfile Dockerfile.claude "
        }
        powerShell {
            name = "Merge upstream"
            id = "UpstreamMerge"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalamaconsolidated-2026.1 -Dockerfile Dockerfile.claude -NoBuildImage -Snapshot upstream-merge --timeout %UpstreamMerge.Timeout% %UpstreamMerge.Arguments%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

    dependencies {
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_Metalama_UpstreamMerge")) {
            snapshot {
                     onDependencyFailure = FailureAction.ADD_PROBLEM
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Community"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity_UpstreamMerge")) {
            snapshot {
                     onDependencyFailure = FailureAction.ADD_PROBLEM
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_UpstreamMerge")) {
            snapshot {
                     onDependencyFailure = FailureAction.ADD_PROBLEM
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Documentation"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation_UpstreamMerge")) {
            snapshot {
                     onDependencyFailure = FailureAction.ADD_PROBLEM
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Premium"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaPremium_UpstreamMerge")) {
            snapshot {
                     onDependencyFailure = FailureAction.ADD_PROBLEM
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/private/**/*=>dependencies/Metalama.Samples"
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaSamples_UpstreamMerge")) {
            snapshot {
                     onDependencyFailure = FailureAction.ADD_PROBLEM
            }
        }
        dependency(AbsoluteId("Metalama_Metalama20261_MetalamaTests_MetalamaTestsNopCommerce_DebugBuild")) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
     }

})

object Bump : BuildType({

    name = "Bump Versions"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Execute Orchestrator.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_MetalamaConsolidated"))
        root(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler"),
          """+:. => source-dependencies/Metalama.Compiler""")
        root(AbsoluteId("Metalama_Metalama20261_Metalama"),
          """+:. => source-dependencies/Metalama""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity"),
          """+:. => source-dependencies/Metalama.Community""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaPremium"),
          """+:. => source-dependencies/Metalama.Premium""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaSamples"),
          """+:. => source-dependencies/Metalama.Samples""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation"),
          """+:. => source-dependencies/Metalama.Documentation""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaTestsNopCommerce"),
          """+:. => source-dependencies/Metalama.Tests.NopCommerce""")
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalamaconsolidated-2026.1"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalamaconsolidated-2026.1 "
        }
        powerShell {
            name = "Execute Orchestrator.ps1"
            id = "Exec"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Orchestrator.ps1 -ImageName metalamaconsolidated-2026.1 -NoBuildImage bump %Exec.Arguments%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

})

object PrePublish : BuildType({

    name = "Prepare Deployment"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Execute Orchestrator.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_MetalamaConsolidated"))
        root(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler"),
          """+:. => source-dependencies/Metalama.Compiler""")
        root(AbsoluteId("Metalama_Metalama20261_Metalama"),
          """+:. => source-dependencies/Metalama""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity"),
          """+:. => source-dependencies/Metalama.Community""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaPremium"),
          """+:. => source-dependencies/Metalama.Premium""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaSamples"),
          """+:. => source-dependencies/Metalama.Samples""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation"),
          """+:. => source-dependencies/Metalama.Documentation""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaTestsNopCommerce"),
          """+:. => source-dependencies/Metalama.Tests.NopCommerce""")
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalamaconsolidated-2026.1"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalamaconsolidated-2026.1 "
        }
        powerShell {
            name = "Execute Orchestrator.ps1"
            id = "Exec"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Orchestrator.ps1 -ImageName metalamaconsolidated-2026.1 -NoBuildImage prepublish %Exec.Arguments%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

})

object PostPublish : BuildType({

    name = "Finalize Deployment"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Execute Orchestrator.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_MetalamaConsolidated"))
        root(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler"),
          """+:. => source-dependencies/Metalama.Compiler""")
        root(AbsoluteId("Metalama_Metalama20261_Metalama"),
          """+:. => source-dependencies/Metalama""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaCommunity"),
          """+:. => source-dependencies/Metalama.Community""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaPremium"),
          """+:. => source-dependencies/Metalama.Premium""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaSamples"),
          """+:. => source-dependencies/Metalama.Samples""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaDocumentation"),
          """+:. => source-dependencies/Metalama.Documentation""")
        root(AbsoluteId("Metalama_Metalama20261_MetalamaTestsNopCommerce"),
          """+:. => source-dependencies/Metalama.Tests.NopCommerce""")
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalamaconsolidated-2026.1"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalamaconsolidated-2026.1 "
        }
        powerShell {
            name = "Execute Orchestrator.ps1"
            id = "Exec"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Orchestrator.ps1 -ImageName metalamaconsolidated-2026.1 -NoBuildImage postpublish %Exec.Arguments%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

})

