<Project>
  <PropertyGroup>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2027.0.1-preview</MetalamaVersion>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2027.0.1-preview</MetalamaCompilerVersion>
    <MetalamaCommunityVersion Condition="'$(MetalamaCommunityVersion)' == ''">2027.0.1-preview</MetalamaCommunityVersion>
    <MetalamaSamplesVersion Condition="'$(MetalamaSamplesVersion)' == ''">2027.0.1-preview</MetalamaSamplesVersion>
    <MetalamaVsxVersion Condition="'$(MetalamaVsxVersion)' == ''">2027.0.1</MetalamaVsxVersion>
    <MetalamaConsolidatedReleaseVersion>2027.0.1-preview</MetalamaConsolidatedReleaseVersion>
    <MetalamaConsolidatedReleaseMainVersion>2027.0.1</MetalamaConsolidatedReleaseMainVersion>
    <MetalamaPremiumVersion Condition="'$(MetalamaPremiumVersion)' == ''">2027.0.1-preview</MetalamaPremiumVersion>
    <MetalamaDocumentationVersion Condition="'$(MetalamaDocumentationVersion)' == ''">2027.0.1-preview</MetalamaDocumentationVersion>
  </PropertyGroup>
</Project>