<Project>
  <PropertyGroup>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.20</MetalamaVersion>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.12</MetalamaCompilerVersion>
    <MetalamaCommunityVersion Condition="'$(MetalamaCommunityVersion)' == ''">2026.1.20</MetalamaCommunityVersion>
    <MetalamaSamplesVersion Condition="'$(MetalamaSamplesVersion)' == ''">2026.1.20</MetalamaSamplesVersion>
    <MetalamaVsxVersion Condition="'$(MetalamaVsxVersion)' == ''">2026.1.0</MetalamaVsxVersion>
    <MetalamaConsolidatedReleaseVersion>2026.1.20</MetalamaConsolidatedReleaseVersion>
    <MetalamaConsolidatedReleaseMainVersion>2026.1.20</MetalamaConsolidatedReleaseMainVersion>
    <MetalamaPremiumVersion Condition="'$(MetalamaPremiumVersion)' == ''">2026.1.20</MetalamaPremiumVersion>
    <MetalamaDocumentationVersion Condition="'$(MetalamaDocumentationVersion)' == ''">2026.1.20</MetalamaDocumentationVersion>
  </PropertyGroup>
</Project>