# escape=`

# This file is auto-generated by PostSharp.Engineering.

ARG WINDOWS_VERSION=ltsc2025
FROM mcr.microsoft.com/windows/servercore:${WINDOWS_VERSION}

# The initial shell is Windows PowerShell (use full path to avoid HCS issues)
SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]

# Prepare environment
ENV PSExecutionPolicyPreference=Bypass
ENV POWERSHELL_UPDATECHECK=Off
ENV TEMP=C:\Temp
ENV TMP=C:\Temp
ENV RUNNING_IN_DOCKER=TRUE

# Set locale for consistent behavior regardless of host locale
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV DOTNET_CLI_UI_LANGUAGE=en
ENV VSLANG=1033

# Set base PATH explicitly to avoid issues with expansion
ENV PATH="C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0"

# Enable long path support
RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1



# Install VS Build Tools
COPY VisualStudio.17.14.15.Release.chman /VisualStudio.17.14.15.Release.chman
RUN Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe; `
    $process = Start-Process .\vs_buildtools.exe -NoNewWindow -Wait -PassThru `
        -ArgumentList  "--quiet", "--wait", "--norestart", "--nocache",  "--installPath", "C:\BuildTools", "--installChannelUri", "c:\VisualStudio.17.14.15.Release.chman", "--installCatalogUri", "https://download.visualstudio.microsoft.com/download/pr/eb5f7427-d28f-4e06-95cc-093f6c2070c8/3480d7a528bad877857c92843bb1e9ce8ebd48a2bffcee366a98a7343f4d32fb/VisualStudio.vsman", "--productId", "Microsoft.VisualStudio.Product.BuildTools", "--add", "Microsoft.Component.MSBuild", "--add", "Microsoft.NetCore.Component.SDK", "--add", "Microsoft.Net.Component.4.7.2.TargetingPack", "--add", "Microsoft.Net.Component.4.7.2.SDK", "--add", "Microsoft.Net.Component.4.8.TargetingPack", "--add", "Microsoft.Net.Component.4.8.SDK"; `        
    if ($process.ExitCode -ne 0) { `
     Get-ChildItem "$env:TEMP\dd_*.log" -ErrorAction SilentlyContinue | ForEach-Object { `
        Write-Host "=== Contents of $($_.Name) ==="; `
        Get-Content $_.FullName; `
        Write-Host "=== End of $($_.Name) ===" `
        }; `
     exit $process.ExitCode; `
     }; `
    Remove-Item C:\\vs_buildtools.exe;
ENV VSINSTALLDIR=C:\BuildTools
RUN New-Item -ItemType Directory -Path 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages' -Force | Out-Null"; `
    New-Item -ItemType Directory -Path 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder' -Force | Out-Null
