# escape=`

# This file is auto-generated by PostSharp.Engineering.

ARG WINDOWS_VERSION=ltsc2025
ARG OS_IMAGE_REPOSITORY=mcr.microsoft.com/windows/servercore
FROM ${OS_IMAGE_REPOSITORY}:${WINDOWS_VERSION}

# The initial shell is Windows PowerShell (use full path to avoid HCS issues)
SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]

# Prepare environment
ENV PSExecutionPolicyPreference=Bypass
ENV POWERSHELL_UPDATECHECK=Off
ENV TEMP=C:\Temp
ENV TMP=C:\Temp
ENV RUNNING_IN_DOCKER=TRUE

# Set locale for consistent behavior regardless of host locale
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV DOTNET_CLI_UI_LANGUAGE=en
ENV VSLANG=1033

# Set base PATH explicitly to avoid issues with expansion
ENV PATH="C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0"

# Enable long path support
RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1



# Install VS Build Tools
COPY VisualStudio.18.9.2.Release.chman /VisualStudio.18.9.2.Release.chman
RUN Invoke-WebRequest -Uri https://aka.ms/vs/18/stable/vs_buildtools.exe -OutFile C:\vs_buildtools.exe
RUN $process = Start-Process C:\vs_buildtools.exe -NoNewWindow -Wait -PassThru `
        -ArgumentList "--quiet", "--wait", "--norestart", "--nocache", "--installPath", "C:\BuildTools", "--installChannelUri", "C:\VisualStudio.18.9.2.Release.chman", "--installCatalogUri", "https://download.visualstudio.microsoft.com/download/pr/fe4fb3e6-ea32-4ae3-b154-72821a274f0d/29d05070615bd4bbe095bee9716d248be7661e516424fb9d06597ce4f3ab99ca/VisualStudio.vsman", "--productId", "Microsoft.VisualStudio.Product.BuildTools"; `
    if ($process.ExitCode -ne 0) { `
        Get-ChildItem "$env:TEMP\dd_*.log" -ErrorAction SilentlyContinue | ForEach-Object { `
            Write-Host "=== Contents of $($_.Name) ==="; `
            Get-Content $_.FullName; `
            Write-Host "=== End of $($_.Name) ===" `
        }; `
        exit $process.ExitCode; `
    }
RUN $process = Start-Process C:\vs_buildtools.exe -NoNewWindow -Wait -PassThru `
        -ArgumentList "modify", "--quiet", "--wait", "--norestart", "--nocache", "--installPath", "C:\BuildTools", "--channelId", "VisualStudio.18.Release", "--productId", "Microsoft.VisualStudio.Product.BuildTools", "--add", "Microsoft.Component.MSBuild", "--add", "Microsoft.Net.Component.4.7.2.SDK", "--add", "Microsoft.Net.Component.4.7.2.TargetingPack"; `
    if ($process.ExitCode -ne 0) { `
        Get-ChildItem "$env:TEMP\dd_*.log" -ErrorAction SilentlyContinue | ForEach-Object { `
            Write-Host "=== Contents of $($_.Name) ==="; `
            Get-Content $_.FullName; `
            Write-Host "=== End of $($_.Name) ===" `
        }; `
        exit $process.ExitCode; `
    }
RUN $process = Start-Process C:\vs_buildtools.exe -NoNewWindow -Wait -PassThru `
        -ArgumentList "modify", "--quiet", "--wait", "--norestart", "--nocache", "--installPath", "C:\BuildTools", "--channelId", "VisualStudio.18.Release", "--productId", "Microsoft.VisualStudio.Product.BuildTools", "--add", "Microsoft.NetCore.Component.SDK", "--add", "Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools", "--add", "Microsoft.VisualStudio.Workload.MSBuildTools"; `
    if ($process.ExitCode -ne 0) { `
        Get-ChildItem "$env:TEMP\dd_*.log" -ErrorAction SilentlyContinue | ForEach-Object { `
            Write-Host "=== Contents of $($_.Name) ==="; `
            Get-Content $_.FullName; `
            Write-Host "=== End of $($_.Name) ===" `
        }; `
        exit $process.ExitCode; `
    }
RUN $process = Start-Process C:\vs_buildtools.exe -NoNewWindow -Wait -PassThru `
        -ArgumentList "modify", "--quiet", "--wait", "--norestart", "--nocache", "--installPath", "C:\BuildTools", "--channelId", "VisualStudio.18.Release", "--productId", "Microsoft.VisualStudio.Product.BuildTools", "--add", "Microsoft.VisualStudio.Workload.NetCoreBuildTools"; `
    if ($process.ExitCode -ne 0) { `
        Get-ChildItem "$env:TEMP\dd_*.log" -ErrorAction SilentlyContinue | ForEach-Object { `
            Write-Host "=== Contents of $($_.Name) ==="; `
            Get-Content $_.FullName; `
            Write-Host "=== End of $($_.Name) ===" `
        }; `
        exit $process.ExitCode; `
    }
ENV VSINSTALLDIR=C:\BuildTools
RUN New-Item -ItemType Directory -Path 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages' -Force | Out-Null"; `
    New-Item -ItemType Directory -Path 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder' -Force | Out-Null
