# escape=`

# This file is auto-generated by PostSharp.Engineering.

ARG BASE_IMAGE=agent-vs17.Dockerfile
FROM ${BASE_IMAGE}

# The base image's shell is Windows PowerShell (use full path to avoid HCS issues)
SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]



# Install Git
RUN Invoke-WebRequest -Uri https://github.com/git-for-windows/git/releases/download/v2.50.0.windows.1/PortableGit-2.50.0-64-bit.7z.exe -OutFile PortableGit.exe; `
    Start-Process -FilePath .\PortableGit.exe -ArgumentList '-o"C:\git"', '-y' -Wait; `
    Remove-Item PortableGit.exe

# Add git to PATH using ENV directive (persists across shell switches)
ENV PATH="C:\git\cmd;C:\git\bin;C:\git\usr\bin;${PATH}"

RUN git config --system core.longpaths true; git config --system core.autocrlf false

# Set CLAUDE_CODE_GIT_BASH_PATH for Claude Code
ENV CLAUDE_CODE_GIT_BASH_PATH=C:\git\bin\bash.exe


# Install PowerShell 7
RUN Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.5.2/PowerShell-7.5.2-win-x64.msi -OutFile PowerShell.msi; `
    $process = Start-Process msiexec.exe -Wait -PassThru -ArgumentList '/I PowerShell.msi /quiet'; `
    if ($process.ExitCode -ne 0) { exit $process.ExitCode }; `
    Remove-Item PowerShell.msi

ENV PATH="C:\Program Files\PowerShell\7;${PATH}"


# Download .NET Installer
RUN Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1

# Add .NET to PATH using ENV directive (persists across shell switches)
ENV PATH="C:\Program Files\dotnet;${PATH}"


# Install .NET Sdk 8.0.417
RUN & .\dotnet-install.ps1 -Version 8.0.417 -InstallDir 'C:\Program Files\dotnet'


# Install .NET Sdk 9.0.310
RUN & .\dotnet-install.ps1 -Version 9.0.310 -InstallDir 'C:\Program Files\dotnet'


# Install .NET Sdk 10.0.102
RUN & .\dotnet-install.ps1 -Version 10.0.102 -InstallDir 'C:\Program Files\dotnet'


# Install .NET Sdk 10.0.106
RUN & .\dotnet-install.ps1 -Version 10.0.106 -InstallDir 'C:\Program Files\dotnet'


# .NET Dump Tool
RUN dotnet tool install --global dotnet-dump;

ENV PATH="C:\Users\ContainerAdministrator\.dotnet\tools;${PATH}"


# Install GitHub CLI
RUN Invoke-WebRequest -Uri https://github.com/cli/cli/releases/download/v2.63.2/gh_2.63.2_windows_amd64.msi -OutFile gh.msi; `
    $process = Start-Process msiexec.exe -Wait -PassThru -ArgumentList '/I gh.msi /quiet'; `
    if ($process.ExitCode -ne 0) { exit $process.ExitCode }; `
    Remove-Item gh.msi

ENV PATH="C:\Program Files\GitHub CLI;${PATH}"


# Install Azure CLI
RUN Invoke-WebRequest -Uri https://aka.ms/installazurecliwindowsx64 -OutFile AzureCLI.msi; `
    $process = Start-Process msiexec.exe -Wait -PassThru -ArgumentList '/I AzureCLI.msi /quiet'; `
    if ($process.ExitCode -ne 0) { exit $process.ExitCode }; `
    Remove-Item AzureCLI.msi

ENV PATH="C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin;${PATH}"


# Epilogue
# Configure .NET SDK
ENV DOTNET_NOLOGO=1
